# Generated by Django 4.1.3 on 2022-11-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_post',
            new_name='date_post',
        ),
    ]
