# Generated by Django 4.1.3 on 2022-12-06 18:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_author_post_alter_post_category_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_post',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
    ]
