# Generated by Django 4.1.3 on 2022-12-06 18:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_content_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2_post',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Content2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_post',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
