# Generated by Django 4.1.3 on 2022-12-06 20:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_content2_post_alter_post_content_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content2_post',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content2'),
        ),
    ]
