# Generated by Django 4.1.3 on 2022-12-06 20:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_content2_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content2_post',
        ),
        migrations.AlterField(
            model_name='post',
            name='content_post',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
    ]
